### ISSUE TITLE
Installation ERROR:  make: command not found

### ISSUE THREAD

**Issue by samiurprapon** [CineEncoder/CineEncoder#27]
OS: Manjaro Linux x86_64 
Kernel: 5.16.11-arch1-g14-2 
DE: GNOME 41.4

Command : `yay -S cine-encoder`

Output: 
```bash
Info: creating stash file ~/.cache/yay/cine-encoder/src/cine-encoder-3.5.2/builddir/.qmake.stash
~/.cache/yay/cine-encoder/PKGBUILD: line 18: make: command not found

```

**Comment by CineEncoder** [comment]
Hello! 
Take a ready-made package for manjaro
https://github.com/CineEncoder/cine-encoder/releases/download/3.5.2/cine-encoder-3.5.2_manjaro_x86_64.pkg.tar.zst

**Comment by samiurprapon** [comment]
Thank you.
