### ISSUE TITLE
Error "Specified rc mode is deprecated." with newer FFMPEG application

### ISSUE THREAD

**Issue by hnsteyding** [CineEncoder/CineEncoder#31]
Hello,

i replace the existing ffmpeg application with a newer one and get the following error:

[h264_nvenc @ 000001abf9b4d640] Specified rc mode is deprecated.
[h264_nvenc @ 000001abf9b4d640] Use -rc constqp/cbr/vbr, -tune and -multipass instead.
[h264_nvenc @ 000001abf9b4d640] InitializeEncoder failed: invalid param (8): Presets P1 to P7 are not supported with older 2 Pass RC Modes(CBR_HQ, VBR_HQ) and cbr lowdelay.
Enable NV_ENC_RC_PARAMS::multiPass flag for two pass encoding a
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

According to 
http://git.videolan.org/gitweb.cgi/ffmpeg.git/?a=commit;h=cde3c080338154cc73103939f6ab26ae5bb718cd

these ffmpeg option is dropped out / has been changed ("Use -rc constqp/cbr/vbr, -tune and -multipass instead")

i have attached my preset.

Could you fix these option in the next version ?

Thank you.

[presets.zip](https://github.com/CineEncoder/cine-encoder/files/8330432/presets.zip)

**Comment by CineEncoder** [comment]
Hi! 
OK, I will try to solve this problem.

**Comment by CineEncoder** [comment]
Hello! I fixed this bug and published a new release.

**Comment by hnsteyding** [comment]
Thanks.
Now ist's working.
