### ISSUE TITLE
[X11, Qt 5.15.3] Spinner animation takes 100% CPU

### ISSUE THREAD

**Issue by marek-g** [CineEncoder/CineEncoder#33]
First of all thanks for this encoder. It is the only open source GUI available for Linux that meets my goals!!

I have found that the spinner animation takes 100% of one CPU core during encoding. This breaks the benefits of being energy efficient when using hardware encoders. I have found that this is because of a bug in the QMovie class when playing GIF animations:

https://bugzilla.redhat.com/show_bug.cgi?id=61928
https://bugreports.qt.io/browse/QTBUG-2441
(although it says it is closed, it's not fixed for me)

My current workaround is to comment out both "animation->start();" lines in the mainwindow.cpp files. So, I'm ok with this fix. I just wonder if you know about any other alternatives to GIF animations?

**Comment by CineEncoder** [comment]
Hello! Thanks for the feedback.

> I have found that the spinner animation takes 100% of one CPU core during encoding.

No, I didn't pay attention to it, I thought everything was working clearly. I'll check it out.

> I just wonder if you know about any other alternatives to GIF animations?

There are no ideas about this yet, most likely, in this case I will have to make my own implementation, which will be similar to animation.

**Comment by CineEncoder** [comment]
Hello! Fixed. Replaced QMovie with a custom animation class.

**Comment by marek-g** [comment]
Thanks!!!
