### ISSUE TITLE
Setting 2-pass seems to yield an error during conversion

### ISSUE THREAD

**Issue by philstopford** [CineEncoder/CineEncoder#45]
I'm finding that there mere act of switching to 2-pass breaks the encode. 

This works:

HEVC, Res: Source, Fps: Source, YUV, 4:2:0, 8 bit, CRF 25, Preset: Fast, 1 Pass, Audio: AAC, 256k, MP4

This fails:

HEVC, Res: Source, Fps: Source, YUV, 4:2:0, 8 bit, CRF 25, Preset: Fast, 2 Pass, Audio: AAC, 256k, MP4

The error message seems to be truncated, so doesn't give any information to report.

**Comment by CineEncoder** [comment]
The CRF mode is selected here, because of this an error occurs, as far as I understand, ffmpeg only works for one pass in this mode. The full log can be viewed via View->Log

**Comment by philstopford** [comment]
OK. Wonder if it might be possible to screen incompatible options, but I can see that would also be a lot of work.

**Comment by CineEncoder** [comment]
I have already fixed this, I will test it a little and publish it one of these days.
