### ISSUE TITLE
GUI: Close, Expand and Hide button not visible

### ISSUE THREAD

**Issue by hnsteyding** [CineEncoder/CineEncoder#48]
After compiling Cinecoder from actual source there is no close, expand and hide button visible.

![Close, Expand and Hide button not visible](https://user-images.githubusercontent.com/65712636/174407712-ef81802b-524c-4382-b9b6-c98e69d53409.jpg)

Compile environment:
Windows 10
MinGW x64
Qt version 5.15.3

is this a "known" issue ?

Regards,
Mark.

**Comment by CineEncoder** [comment]
Hello! Try to rebuild the project from the master branch, I recently made a correction for this problem. Also add the library to the folder where the project is being assembled: builddir/imageformats/qsvg.dll (you can take the library from your Qt). Check the folder structure (you can see a sample in a portable build for Windows).

**Comment by hnsteyding** [comment]
Hello. Works now !.
Thank you.
