### ISSUE TITLE
Current code only appears to support adding 32 files in a drag-and-drop manner

### ISSUE THREAD

**Issue by philstopford** [CineEncoder/CineEncoder#56]
Shift select more than 32 files and drag and drop them into the tool. Only 32 appear to be added. The GUI appears to only handle 32 items for drag-and-drop, requiring batches to be added. My primary desktop is Cinnamon, but I also see this with Cosmic under Pop_OS 22.04. I've not yet tried under KDE or similar.

**Comment by CineEncoder** [comment]
Hello!
Yes, I added this restriction on purpose. The files open for quite a long time, I did it so that there would not be a situation of hanging for too long.

**Comment by philstopford** [comment]
Hmm. I noticed that the time to add each member of the group being dragged-and-dropped gets longer. That slightly surprised me. However, it's not all that painful and the silent failure to add more than 32 feels like a bug rather than intentional design. The delay itself is also not a huge problem because you do display progress indicators as you are adding files, so it doesn't seem like the application is hanging.

I would suggest a re-think here might be helpful, or allow the user to disable/configure the limit to their own taste.

**Comment by CineEncoder** [comment]
Although, indeed, there is little benefit from this restriction.

**Comment by philstopford** [comment]
https://github.com/CineEncoder/cine-encoder/pull/61
