### ISSUE TITLE
Ability to clear the list?

### ISSUE THREAD

**Issue by philstopford** [CineEncoder/CineEncoder#58]
The list doesn't seem to have a way to empty it out; it would be neat to have a way to clear it (e.g. after a batch conversion), to avoid having to re-start the tool or remove each of the entries one-by-one

**Comment by CineEncoder** [comment]
Hello! 
Ok. I will add an additional button for cleaning.

**Comment by philstopford** [comment]
https://github.com/CineEncoder/cine-encoder/pull/60
